### ISSUE TITLE
Consider adding AMD support

### ISSUE THREAD

**Issue by roysanchez** [aspnet/jquery-validation-unobtrusive#12]
consider adding AMD support. I can do a Pull Request.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by DamianEdwards** [comment]
Yeah that would be great. Perhaps make it [UMD](https://github.com/umdjs/umd) instead so it works "everywhere"?

**Comment by ryanelian** [comment]
Just chiming in while this issue is not addressed.

At the moment, I'm using Gulp + Browserify as part of my client-side project management. This is what my entry point and setup for ASP.NET MVC Validation looks like using the tools:

![aspnet-entry](https://cloud.githubusercontent.com/assets/8892187/17143571/e56366ec-537d-11e6-8486-15547dc1fc4c.PNG)

![aspnet-validate](https://cloud.githubusercontent.com/assets/8892187/17143578/e92ff9ac-537d-11e6-8e11-2d85b948eb67.PNG)

As you can see it's abit hacky due to `jquery-validation-unobtrusive` requireing a global variable of `jQuery`. I truly wish that I can do this:

```javascript
require('jquery');
require('jquery-validation');
require('jquery-validation-unobtrusive');
```

Can we have this feature soon? Thanks in advance! :+1:

**Comment by Eilon** [comment]
@ryanelian would https://github.com/aspnet/jquery-validation-unobtrusive/pull/13 address this?

It just hasn't been a high priority for us because we haven't seen a whole lot of interest in that space. But if there is, we can reconsider.

**Comment by ryanelian** [comment]
Unfortunately #13 didn't address this although it is on the right track. I've tried loading https://github.com/roysanchez/jquery-validation-unobtrusive/blob/master/jquery.validate.unobtrusive.js by putting it into the same folder as the source then using something like:

```javascript
require('jquery');
require('jquery-validation');
require('./jquery.validate.unobtrusive');
```

Here's what happened:

1. It's supposed to load `jquery-validation` instead of `jquery.validate` module. `[00:28:02] { Error: Cannot find module 'jquery.validate'`

2. Changing the `jquery-validation` module removes the error but unfortunately the resulting bundle didn't trigger the client-side validation. I'm not sure why, but I'm probably not qualified to debug this.

**Comment by Eilon** [comment]
@DamianEdwards any thoughts on adding support for this? Seems like a nice bit of value we can add.

**Comment by DamianEdwards** [comment]
Yep would be great to do it. We should investigate the UMD pattern rather than just implement AMD though.

**Comment by ryanelian** [comment]
Yay.

Also probably should look into whether `jquery-validation-unobtrusive` can be required stand-alone (without requiring `jquery` and `jquery-validation`) in Browserify after being converted into UMD module.

So instead of writing this (existing):

```javascript
global.jQuery = require('jquery');

require('jquery-validation');

// But jquery.validate.unobtrusive requires that jQuery is defined globally!
require('jquery-validation-unobtrusive');
```

I can just do this instead (This may require updating the `jquery-validation-unobtrusive` NPM package so that it has dependency on `jquery` and `jquery-validation`. Currently it doesn't.):

```javascript
require('jquery-validation-unobtrusive');
```

That'd be a godsend.

**Comment by Eilon** [comment]
@ryanbrandenburg please have fun learning about script loading 😄

**Comment by ryanbrandenburg** [comment]
For those of you following along at home [this](https://github.com/jzaefferer/jquery-validation/issues/1829) issue sounds like they'll be fixing jquery-validation to export jquery without the putting it in global. We'll wait to finish up this work until that's available, it should be a pretty quick and clean fix after that's done.

**Comment by ryanbrandenburg** [comment]
jquery-validation has taken my PR to fix they're issue, and now we're waiting for it to be available on bower.

**Comment by ryanelian** [comment]
I just found out that JQuery Validation 1.16.0 was outed with your fix last December. 

I thought I'd let you know about it.

**Comment by Eilon** [comment]
@ryanelian cool! @ryanbrandenburg ping!

**Comment by ryanbrandenburg** [comment]
Excellent! I'll get to this after the current batch of items I've started work on.

**Comment by Eilon** [comment]
@ryanbrandenburg is this fixed?

**Comment by ryanbrandenburg** [comment]
Yes, updated.
