### ISSUE TITLE
data-val-required and input type=checkbox does not work

### ISSUE THREAD

**Issue by rmacfadyen** [aspnet/jquery-validation-unobtrusive#139]
Adding a required validation to a checkbox does not work (min repro fiddle https://jsfiddle.net/ho6ngv7t/1/).

The code specifically ignores required & checkbox with the comment "jQuery Validate equates "required" with "mandatory" for checkbox elements". It's unclear what the implied difference is between required and mandatory.

Required checkboxes are unusual, but not uncommon. The common use case of a required/mandatory checkbox is to indicate a user must "Accept terms and conditions" before proceeding.

The fix is to delete lines 382, 383 and 385.

The following workaround corrects the issue:

    //
    // Fix unobtrusive and checkbox
    //
    $.each($.validator.unobtrusive.adapters, function (idx, el) {
        if (el.name === 'required') {
            el.adapt = function (options) {
                options.rules['required'] = true;
                if (options.message) {
                    options.messages['required'] = options.message;
                }
            }
        }
    })
    $.validator.unobtrusive.parse(document);

**Comment by Khaos66** [comment]
This issue has cost me all morning. Because of this the `minlength` validation of a group of checkboxes isn't working, too.
Example: https://jsfiddle.net/2dbafshw/

The issue with `minlength` is, that the `minlength` validator checks if the field is `optional` (not marked as required) and returns `dependency-mismatch` instead of `false`, when the minimum amount of checked checkboxes isn't reached.

Here is an example of 'vanilla' jquery-validate: http://jsfiddle.net/psqn2wco/
You see the same issue. But if you add `required: true` to the rules of `foo`, then the validation is working correctly.

As @rmacfaden pointed out, it is not clear what this comment is refering to:
> jQuery Validate equates "required" with "mandatory" for checkbox elements

To use `minlength` for checkboxes we need `required`, because of the `optional` check!

**Comment by Khaos66** [comment]
@mkArtakMSFT what's your take on this?

**Comment by Khaos66** [comment]
I fixed this very un-unobtrusivy via
```js
$(function() {
    var validator = $("#myForm").data("validator");
    for (var i in validator.settings.rules) {
        var rule = validator.settings.rules[i];
        if (rule.minlength !== undefined && rule.required === undefined) {
            $.extend(validator.settings.messages[i], { required: 'Select a checkbox' });
            $.extend(rule, { required: true });
        }
    }

    console.log(validator.settings);
});
```

**Comment by mkArtakMSFT** [comment]
Thanks for sharing your solution, @Khaos66.
Given there are not much community involvement on this issue nor it's a security issue we're going to close this.
