### ISSUE TITLE
Resetting a form does not reset validation message properly

### ISSUE THREAD

**Issue by rjgotten** [aspnet/jquery-validation-unobtrusive#46]
https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/jquery.validate.unobtrusive.js#L102-L110 only removes the CSS classes.

When resetting a form to an unvalidated state, the validation message content should also be erased and the link between validated input field and error message that is established by the `aria-describedby` attribute should be severed by removing the attribute from the input.

**Comment by Eilon** [comment]
@rjgotten thanks for reporting this, we'll take a look. Can you provide more info on what doesn't work?

I also don't see any mention of `aria-describedby` in the JS code - is that done by jQuery Validate itself?

**Comment by Eilon** [comment]
@ryanbrandenburg can you look into this?

**Comment by maliming** [comment]
@Eilon [https://github.com/aspnet/jquery-validation-unobtrusive/issues/52](url)

**Comment by maliming** [comment]
@Eilon I have the same problem

**Comment by ryanbrandenburg** [comment]
Emptying the span (as I interpreted your suggested fix) would be one way to fix this, but my understanding is that a simpler way would be to just include a .css file on your page with `.validation-summary-valid { display:none; }`. Maybe we should add a "default" css file?

**Comment by rjgotten** [comment]
It's not just the summary that's affected. It's also all the individual messages.

And setting the `validation-summary-valid` and `field-validation-valid` classes to `display:none` is only an option if they are not used in a particular site's styles in other ways. E.g. `field-validation-valid` could be in use by site devs to display a checkmark for properly validated fields.

This also does not resolve the problems with the aria binding set up by the `aria-describedby` attribute, which indeed is added by the core jQuery.validate library.

**Comment by Eilon** [comment]
MVC's validation features do require that apps provide a few common CSS styles by default, e.g. the ones in each app's site.css: https://github.com/aspnet/MusicStore/blob/ca0cf58fe27ef0f11e0bf7fb71d118dbff801e83/samples/MusicStore/wwwroot/Content/Site.css#L19-L42

You can see the list of required CSS styles here: https://github.com/aspnet/Mvc/blob/8f8bf5af341b5cc07e0611dc9a3a02e471e2bf63/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/HtmlHelper.cs#L25-L30

The critical thing is that all the "xyz-valid" styles typically need to have `display:none` set so that they're hidden.

And I believe that once an element is hidden, its ARIA settings aren't as important.

**Comment by rjgotten** [comment]
> @Eilon 
> And I believe that once an element is hidden, its ARIA settings aren't as important.

You believe wrong. Attributes such as `aria-describedby` or  `aria-labeledby`  ignore the hidden/visible state of the element(s) they refer to. That is by design. You can even add `aria-hidden="true"` to such a target element and assistive technology will *still* source the text of it.

See: https://www.paciellogroup.com/blog/2015/05/short-note-on-aria-labelledby-and-aria-describedby/

**Comment by ryanbrandenburg** [comment]
[This](https://github.com/jzaefferer/jquery-validation/issues/1299) issue seems to show that left-over `aria-describedby` attributes are A) caused by jQuery.Validation, not jQuery.Validation.Unobtrusive B) intentional on the part of jquery-validation (rightly or wrongly). That being the case (unless I missed something) I would suggest filing the `aria-describedby` stuff against them.  That said, we still have the reset problem. Excluding `aria-describedby` concerns would seem to make having default style rules an acceptable answer, no?

**Comment by Eilon** [comment]
@rjgotten the various styles I'm referring to were actually supposed to be in the MVC templates but they got removed for an unknown reason. We tried tracking down why it happened but weren't able to find out why. They used to be in MVC templates a long time ago. The jQuery Validation Unobtrusive library here fundamentally requires having those CSS styles defined - it is just by sheer coincidence that it happens to appear to work most of the time (though obviously not in the case described here).

**Comment by rjgotten** [comment]
> @Eilon 
> The jQuery Validation Unobtrusive library here fundamentally requires having those CSS styles defined

What fundamental requirement? The validate.unobtrusive source code doesn't even access `jQuery.fn.css` or the plain old `HTMLElement.style` property. Without any kind styles applied for the class names used by MVC validation, the only thing which doesn't work correctly from a functional perspective is the fact that errors are not emptied out when a form is reset.

Everything else, including emptying them out when a form shifts from error to valid state, ... just works.

> @ryanbrandenburg 
> This issue seems to show that left-over aria-describedby attributes are A) caused by jQuery.Validation, not jQuery.Validation.Unobtrusive B) intentional on the part of jquery-validation (rightly or wrongly). That being the case (unless I missed something) I would suggest filing the aria-describedby stuff against them.

The core jQuery.validation framework empties out error messages, also when its `resetForm` method is called. In that case, the `aria-describedby` attribute is harmless, because there is no content left to read.

You don't get to benefit from that, because jQuery.Validation.Unobtrusive does not call `resetForm` as part of its `onReset` handler.

**Comment by maliming** [comment]
@Eilon @ryanbrandenburg @rjgotten 
i open pr #54 onReset callback not be call.

**Comment by Eilon** [comment]
@rjgotten the fundamental thing about the styles is done at places such as this: https://github.com/aspnet/jquery-validation-unobtrusive/blob/fde966f9e83a7afe5de16a39301cb0db2b01fe20/jquery.validate.unobtrusive.js#L79

The system has always historically required that the styles be present and be defined to have valid things invisible (or at least, *less* visible), and invalid things visible (and, perhaps, be "red" or otherwise error-looking-ish).

I agree it's good to have the error text *also* cleared out for the reasons you mention.

But from a styles and layout perspective having an empty element and having an element with `display:none` is not the same thing, which is why I believe it's important to have *both* of those set.

**Comment by maliming** [comment]
I'm Invisible Man

**Comment by Eilon** [comment]
@maliming sorry, not trying to ignore you, I just want to make sure we understand what the fundamental scenario and requirements are.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
